name: setup-env

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: run dependencies
      shell: bash
      run: |
        npm run deploy
     
