name: setup-env

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v2
      with:
       node-version: '16'
    - name: run dependencies
      shell: bash
      run: |
       npm run deploy
    # - name: Deploy using ssh
      
    #     with:
    #       host: ${{ secrets.HOST }}
    #       username: ${{ secrets.USERNAME }}
    #       key: ${{ secrets.PRIVATE_KEY }}
    #       port: 22
    #       script: |
             
    #         npm run deploy