name: Composite Test
on:
  pull_request:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: composite
        uses: ./.github/actions/setup-composite