name: Composite Test
on:
  pull_request:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
      - name: composite
        uses: ./.github/actions/setup-composite
       