name: Composite Test
on:
  pull_request:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  setup:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: composite
        uses: ./.github/actions/setup-composite
       